services:
  web:
    build: .
    ports:
      - "6555:6543"
    environment:
      CHANNELSTREAM_URL: "http://channelstream:8000"
      DEMO_URL: "http://demo.channelstream.org"
      CHANNELSTREAM_WS_URL: "ws://server.channelstream.org/ws"
    restart: always
  channelstream:
    ports:
      - "8000:8000"
    environment:
      CHANNELSTREAM_ALLOW_POSTING_FROM: "0.0.0.0"
    restart: always
  demo:
    ports:
      - "6544:6544"
    environment:
      CHANNELSTREAM_URL: "http://channelstream:8000"
      CHANNELSTREAM_WS_URL: "ws://server.channelstream.org/ws"
      DEMO_PORT: 6544
    restart: always
