version: '3.2'
services:
  web:
    volumes:
      - type: bind
        source: ./backend
        target: /opt/application
      - type: bind
        source: ./rundir
        target: /opt/rundir
  statics:
    build:
      context: .
      dockerfile: Dockerfile.static
    environment:
      FRONTEND_ASSSET_ROOT_DIR: "/opt/rundir/static"
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
      - type: bind
        source: ./rundir
        target: /opt/rundir
volumes:
  rundir:
  application:
