version: '3.2'
services:
  web:
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /opt/application
        read_only: true
      - type: volume
        source: rundir
        target: /opt/rundir
    command: ["pserve", "--reload", "/opt/rundir/config.ini"]
  statics:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.static
    environment:
      FRONTEND_ASSSET_ROOT_DIR: "/opt/rundir/static"
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
        read_only: true
      - type: volume
        source: rundir
        target: /opt/rundir
volumes:
  rundir: {}
  application: {}
